# -*- coding: utf-8 -*-
"""NumpyExo.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1DuXwWsUlFMTucSsxAS1muaa4HqYPlZdn

# Numpy exercices pratiques
Ce notebook à pour objectif de vous faire pratiquer numpy dans toute sa généralité. 
Vous avez donc une liste de questions à faire ! Il ne faut pas hésiter à faire des recherches sur google ainsi que voir la [documentation officielle](https://docs.scipy.org/doc/numpy-1.13.0/reference/).

#### Q1 : Importer le package numpy
"""

import numpy as np

"""#### Q2 : Afficher la version de numpy et la configuration """

np.version.version
np.show_config

"""#### Q3 : Créer un vecteur nul de taille 10"""

np.zeros(10)

"""#### Q4 : Créer un vecteur null de taille 10 et affecter la valeur 1 à la 4ème place (index 4) du vecteur"""

a = np.zeros(10)
a[3] = 1
a

"""#### Q5 : Créer un vecteur Z de 40 valeurs allant de 10 à 50 """

z = np.arange(10,50)
z

"""#### Q6 : Inverser Z (le premier élément devient donc le dernier)"""

zi = np.flipud(z)
zi

"""#### Q7 : Créer une matrice 3x3 avec des valeurs comprise entre 0 et 8 """

np.arange(0,9).reshape(3,3)

"""#### Q8 : Créer une matrice identié 3x3 """

np.identity(3)

"""#### Q9 : Créer une matrice 3x3x3 avec des valeurs random """

np.random.random(size=(3, 3, 3))

"""#### Q10 : Créer une matrice 10x10 avec des valeurs random et afficher le minimum et maximum de cette matrice"""

mat = np.random.random(size=(10, 10))
mat
np.amin(mat)
np.amax(mat)

"""#### Q11 : Créer une matrice 5x5 avec les valeurs 1,2,3,4 en dessous de la diagonale """

np.diagflat([1,2,3,4],-1)

"""#### Q12 : Créer une liste random de taille 5 et donner la somme de ses éléments  """

sum(np.random.rand(5))

"""#### Q13 : Créer une liste random de taille 5 et donner la moyenne de ses éléments"""

np.mean(np.random.rand(5))

"""#### Q14 : En utilisant une fonction, donner la taille de la liste suivante :
```python 
l = [x for x in range(11)]
```
"""

np.size(l)

"""#### Q15 : Créer un tableau de taille 10 avec des valeurs comprises entre 0 et 1 EXCLUS """

np.random.rand(10)

"""#### Q16 : Soit deux tableau A et B de dimension 1 et de taille 5, créer A et B et afficher True si A et B sont égaux False sinon"""



"""#### Q17 : Convertir un tableau de float32 de dimension 1 et de taille 10 en un tableau de meme taille et dimension mais de type int32"""



"""#### Q18 : Normaliser une matrice random 5x5 
La normalisation d'un nombre X consiste à lui retirer sa moyenne et a diviser le tout par son écart type 
"""



"""#### Q19 : Créer une matrice random `M` 2x2 et donner sa transposer 
L'opération de transposition dans une matrice consiste à échanger les lignes et le colonnes. 
"""



"""#### Q20 : Écrire un petit script qui remplace un élément au hasard dans une matrice de dimension NxN"""



"""#### Q21 : Considérons une matrice de dimension (5,5,3), écrire un script qui multiplie cette matrice par une matrice de dimension (5,5)"""

